### ISSUE TITLE
[apps] Better documentation for app limits

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/developers-documentation#134]
The `limits` field is currently missing from payloads in the dev doc.

- Add `limits` fields in the payload of application (list and show app requests) => https://developers.scalingo.com/apps#list-your-applications and https://developers.scalingo.com/apps#get-a-precise-application
- Explain that the default limits of an app is not returned
- Only limits that was modified by a Scalingo operator is returned in the payload of an application
- Maybe specify the list of app limits type ?

**Comment by EtienneM** [comment]
For now, don't specify the app limits. Let's first add this attribute to the doc, we will see if more doc is needed in the future.
