### ISSUE TITLE
Field `required` is missing for env variables

### ISSUE THREAD

**Issue by btrd** [Scalingo/developers-documentation#190]
https://developers.scalingo.com/scalingo-json-schema/index

User can set a boolean to make an env variables required at 1click creation.

**Comment by EtienneM** [comment]
Can you give an example? I'm not sure I understand this issue

**Comment by btrd** [comment]
field | type | description
-- | -- | --
description | string | Description of the variable to explain what it does
value | string | (if no generator) Default value of the variable
generator | string | (if no value) Use a generator to define a default value
template | string | (if generator is ‘url’ or ‘template’) Template to generate value from

In this table there the field `required` missing.
