### ISSUE TITLE
[Repo Link] Add github repo link documentation

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/developers-documentation#26]

**Comment by johnsudaar** [comment]
See https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/conversation/21571011601

**Comment by EtienneM** [comment]
It lacks the doc about the endpoint to get the list of PRs and branches

**Comment by EtienneM** [comment]
here it is: https://developers.scalingo.com/scm_integrations
