### ISSUE TITLE
Add documentation on the new source repository data coming from related pull requests opened for apps

### ISSUE THREAD

**Issue by yohann-bacha** [Scalingo/developers-documentation#295]
We need to add the `source_repo_name`, and `source_repo_html_url` doc for the endpoint listing the pull requests related to an app.

**Comment by EtienneM** [comment]
@yohann-bacha mention of `source_repo_name` and `source_repo_html_url` have been added in #345 and #346. Is it enough or did you had something else in mind?

**Comment by yohann-bacha** [comment]
It is totally enough. Closing
