### ISSUE TITLE
[one-off] run endpoint need async parameter to its body

### ISSUE THREAD

**Issue by curzolapierre** [Scalingo/developers-documentation#403]
Related to https://github.com/Scalingo/project-items/issues/137

https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700233533?view=List

**Comment by ipfaze** [comment]
As it is no longer possible to start a one-off in "attached" mode (`async` parameter as `false`). We should change the `async` parameter in the api to make it `true` by default.
https://github.com/Scalingo/api/blob/098d9d0bfbef7d970683e2a2fef47525298beeaf/app/models/app.rb#L600 

Also modify the developer-documentation to reflect this change.
https://github.com/Scalingo/developers-documentation/blob/80d04ca9043f1856620958bf0e81aca34c73e303/_scalingo_api/apps.md?plain=1#L721

**Comment by SCedricThomas** [comment]
If I understand well the CLI code, detached one-off are sync?
https://github.com/Scalingo/cli/blob/1f21889d2350892493cf9d1afd9d44b693909ce1/apps/run.go#L108-L110

Why don't we deleted the old async / sync difference and make it transparent to the user?

**Comment by SCedricThomas** [comment]
As has been discussed internally, we should remove the notion of async from the one-off containers feature: https://scalingo.slack.com/archives/C01E42AT2G6/p1714143612821979
