### ISSUE TITLE
[Events] Pagination is still on feature

### ISSUE THREAD

**Issue by ichbinkour** [Scalingo/developers-documentation#41]
The pagination should be in the documentation 

<img width="688" alt="Screenshot 2019-06-27 at 14 13 14" src="https://user-images.githubusercontent.com/23211011/60265343-d0d40780-98e5-11e9-886c-cce7c21c9041.png">

**Comment by johnsudaar** [comment]
It's already explained here: http://developers.scalingo.com/index#pagination
However this yellow block should be a link.
