### ISSUE TITLE
[SCM integrations] Missing doc about various search endpoints

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/developers-documentation#65]
`GET /scm_integrations/:id/search_repos?query=XXX`

`GET /scm_integrations/:id/search_pull_requests?query=XXX`

`GET /scm_integrations/:id/orgs`

**Comment by brandon-welsch** [comment]
Do we want to make these routes usable by any customer ? @Soulou

It seems to me that we had already discussed this before.

**Comment by EtienneM** [comment]
Well they currently are usable by anybody and there is no mechanism to restrict this access.

**Comment by EtienneM** [comment]
ping @Soulou
