### ISSUE TITLE
Search result panel is not entirely visible

### ISSUE THREAD

**Issue by yannski** [Scalingo/developers-documentation#7]
1. The result panel is not entirely visible
2. it seems the result comes from doc.scalingo.com

**Comment by johnsudaar** [comment]
2. seems not true anymore.

**Comment by btrd** [comment]
<img width="381" alt="Capture d’écran 2021-02-25 à 10 57 28" src="https://user-images.githubusercontent.com/1385737/109136294-4269f600-7758-11eb-81c6-8d5631d2e2d9.png">
https://developers.scalingo.com
It still true

**Comment by btrd** [comment]
We upgrade Docsearch to V3 and it fix this bug
